// AUTO-GENERATED by scripts/build-api.ts. Do not edit by hand.
// Regenerate with `npm run build:api` (also runs as `prebuild`).

export interface Counters {
  proyectos: number;
  iniciativasDocumentadas: number;
  adopcionVerificada: number;
  verificadasCatalogo: number;
  seguimiento: number;
  ecosistema: number;
  descartadas: number;
  pendientesMigracion: number;
  instituciones: number;
  legislacion: number;
}

export const COUNTERS: Counters = {
  proyectos: 29,
  iniciativasDocumentadas: 29,
  adopcionVerificada: 6,
  verificadasCatalogo: 6,
  seguimiento: 7,
  ecosistema: 16,
  descartadas: 0,
  pendientesMigracion: 0,
  instituciones: 9,
  legislacion: 7,
};
