// AUTO-GENERATED by scripts/build-api.ts. Do not edit by hand.
// Regenerate with `npm run build:api` (also runs as `prebuild`).

export interface Counters {
  proyectos: number;
  iniciativasDocumentadas: number;
  adopcionVerificada: number;
  verificadasCatalogo: number;
  seguimiento: number;
  ecosistema: number;
  descartadas: number;
  pendientesMigracion: number;
  instituciones: number;
  legislacion: number;
}

export const COUNTERS: Counters = {
  proyectos: 31,
  iniciativasDocumentadas: 31,
  adopcionVerificada: 7,
  verificadasCatalogo: 7,
  seguimiento: 8,
  ecosistema: 16,
  descartadas: 0,
  pendientesMigracion: 0,
  instituciones: 11,
  legislacion: 7,
};
