// AUTO-GENERATED by scripts/build-api.ts. Do not edit by hand.
// Regenerate with `npm run build:api` (also runs as `prebuild`).

export interface Counters {
  proyectos: number;
  instituciones: number;
  legislacion: number;
}

export const COUNTERS: Counters = {
  proyectos: 24,
  instituciones: 7,
  legislacion: 5,
};
